# Generated by Django 3.2.12 on 2022-02-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20220222_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='trainings_goals',
            field=models.TextField(blank=True, null=True, verbose_name='Trainings Goals'),
        ),
    ]
