version: '3.7'

services:
  web:
    build: ../development_debug
    volumes:
      - type: bind
        source: ../../../
        target: /home/wger/src/
      - media:/home/wger/media
    ports:
      - "8000:8000"
      - "9999:9999"
    env_file:
      - ./dev.env
    depends_on:
      - db
      - cache

  db:
    image: postgres:12-alpine
    volumes:
      - wger-postgres-data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=wger
      - POSTGRES_PASSWORD=wger
      - POSTGRES_DB=wger

  cache:
    restart: always
    image: redis:latest
    expose:
      - 6379

volumes:
  wger-postgres-data:
  media:
