name: Build and push Docker images

on:
  push:
    branches:
      - master
  workflow_dispatch:  

env:
  REGISTRY: ghcr.io/fmichelsorg

jobs:
  path-context:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.0.0

      - name: Login to DockerHub
        uses: docker/login-action@v2.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build apache image
        uses: docker/build-push-action@v3.1.1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build dev image
        uses: docker/build-push-action@v3.1.1
        with:
          context: .
          push: true
          file: extras/docker/development/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: ${{env.REGISTRY}}/wger/server:latest,${{env.REGISTRY}}/wger/server:2.1-dev,${{env.REGISTRY}}/wger/devel:latest,${{env.REGISTRY}}/wger/devel:2.1-dev
