name: Build and push Docker images

on:
  push:
    branches:
      - master
  workflow_dispatch:  

env:
  REGISTRY: ghcr.io/fmichelsorg

jobs:
  path-context:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build dev image
        uses: docker/build-push-action@v2.9.0
        with:
          context: .
          push: true
          file: extras/docker/development/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: ${{env.REGISTRY}}/wger/server:latest,${{env.REGISTRY}}/wger/server:2.1-dev,${{env.REGISTRY}}/wger/devel:latest,${{env.REGISTRY}}/wger/devel:2.1-dev
