name: Build and push base Docker images

on:
  push:
    branches:
      - "master"
    paths:
        - 'extras/docker/base/Dockerfile'
  schedule:
    - cron: '0 5 1 * *'
  workflow_dispatch: 

env:
  REGISTRY: ghcr.io/fmichelsorg

jobs:
  path-context:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.0.0

      - name: Login to DockerHub
        uses: docker/login-action@v2.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build base image
        uses: docker/build-push-action@v3.1.1
        with:
          context: .
          push: true
          file: extras/docker/base/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: ${{env.REGISTRY}}/wger/base:latest,${{env.REGISTRY}}/wger/base:2.1-dev